name: appartements
version: 1.0.0
config-version: 2

profile: appartements

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dvf_raw_glob: "data/dvf/raw/*.txt"
  paris_addresses_csv: "data/addresses/paris/adresses-paris.csv"
  reference_no_voie: "204"
  reference_voie: "Rue de Vaugirard"
  reference_code_postal: "75015"
  reference_commune: "Paris"
  search_radius_meters: 500

models:
  appartements:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
